<center><h1> CPE 4040 Spring 2024: Homework 4</h1></center>

### <font color=green> Note: The comments in the solution are colored in green. 

In [7]:
import numpy as np

### Check your Numpy Version

In [8]:
np.__version__

'1.24.3'

<h3>Q1: Checker Board (10 Points)</h3>

### This is a classic "checker board" pattern, such as a chess board. There are many ways to do it.

<font color=green> Approach 1: notice that the matrix is essentially a 3x3 identity matrix, [[1,0,1],[0,1,0],[0,0,1]]repeating 9 times, 3X along column and row axis. You can use `np.tile(arr, reps)`, reps = the number of repetitions of arr along each axis

In [21]:
a = np.eye(3, dtype=int)   # This is an identity matrix
reps = (3, 3)     # reps is a tuple
arr = np.tile(a, reps)
arr

array([[0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0, 1],
       [0, 1, 0, 0, 1, 0, 0, 1, 0],
       [1, 0, 0, 1, 0, 0, 1, 0, 0]])

<font color=green>  Approch 2 - Slicing: use `start:stop:step`, `arr[0::3, ::3]` picks every 3rd element starting from the first element on the row and for every `step` row of the matrix.

In [7]:
arr = np.zeros((9,9),dtype=int)
# rows:0,3,6 columns:0,3,6
arr[::3,::3] = 1
# rows:1,4,7 columns:1,4,7
arr[1::3,1::3] = 1
# rows: 2,5,8 columns: 2,5,8
arr[2::3,2::3] = 1

print(arr)

[[1 0 0 1 0 0 1 0 0]
 [0 1 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1]
 [1 0 0 1 0 0 1 0 0]
 [0 1 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1]
 [1 0 0 1 0 0 1 0 0]
 [0 1 0 0 1 0 0 1 0]
 [0 0 1 0 0 1 0 0 1]]


### <font color=green> Which approach is faster? Let's do a quick profiling.

In [8]:
%%timeit  # Approach 1

a = np.eye(3, dtype=int)   # This is an identity matrix
reps = (3, 3)     # reps is a tuple
arr = np.tile(a, reps)

4.85 µs ± 9.69 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [10]:
%%timeit  # Approach 2

arr = np.zeros((9,9),dtype=int)
# rows:0,3,6 columns:0,3,6
arr[::3,::3] = 1
# rows:1,4,7 columns:1,4,7
arr[1::3,1::3] = 1
# rows: 2,5,8 columns: 2,5,8
arr[2::3,2::3] = 1

1.77 µs ± 4.09 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


### <font color=green> Slicing is usually much faster!

<h3>Q2: Array Indexing and Slicing (12 Points) </h3>

#### Q2.1 Please convert this vector, `np.arange(48)`, into a 8x6 array, i.e, 8 rows and 6 columns. Let's call this array A.

In [11]:
A = np.arange(48).reshape(8,6)  

print ('A =\n', A)

A =
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]]


#### Q2.2 Write codes to extract the elements in columns 2, 3, and 5 from A.

In [12]:
cols = [2, 3, 5]

A[:,cols]

array([[ 2,  3,  5],
       [ 8,  9, 11],
       [14, 15, 17],
       [20, 21, 23],
       [26, 27, 29],
       [32, 33, 35],
       [38, 39, 41],
       [44, 45, 47]])

#### Q2.3 Create a new 3x5 array, with elements from rows 6, 1, 3 of A (in that order). __Hint: use fancy indexing__

In [13]:
rows = [6, 1, 3]

A[rows]

array([[36, 37, 38, 39, 40, 41],
       [ 6,  7,  8,  9, 10, 11],
       [18, 19, 20, 21, 22, 23]])

#### Q2.4 Write codes to extract four elements from A with the following indices (4,2), (5,0), (1,2), (3,3).

In [14]:
rows = [4,5,1,3]
cols = [2,0,2,3]

A[rows, cols]

array([26, 30,  8, 21])

<h3>Q3: Array Processing (15 points)</h3>
<h4>Given a 9-by-9 matrix of random integers from 0 to 99:</h4>

In [15]:
np.random.seed(1)
arr = np.random.randint(100,size=(9,9))
arr

array([[37, 12, 72,  9, 75,  5, 79, 64, 16],
       [ 1, 76, 71,  6, 25, 50, 20, 18, 84],
       [11, 28, 29, 14, 50, 68, 87, 87, 94],
       [96, 86, 13,  9,  7, 63, 61, 22, 57],
       [ 1,  0, 60, 81,  8, 88, 13, 47, 72],
       [30, 71,  3, 70, 21, 49, 57,  3, 68],
       [24, 43, 76, 26, 52, 80, 41, 82, 15],
       [64, 68, 25, 98, 87,  7, 26, 25, 22],
       [ 9, 67, 23, 27, 37, 57, 83, 38,  8]])

<h4>Q3.1 Observe that each 9x9 matrix is essentially nine blocks of 3x3 matrix. Write a Python code to calculate the mean value for each of the 3x3 matrix.</h4>
<h4> Hint: use array slicing to index each of the 9 sub-block.</h4>

### <font color=green>Approach 1: taking all 9 slices one at a time (nothing wrong with that!)

In [17]:
# Going horizontal first
a1 = arr[ :3, :3].mean()
a2 = arr[ :3,3:6].mean()
a3 = arr[ :3, 6: ].mean()

# Going vertical
a4 = arr[3:6, :3].mean()
a5 = arr[3:6,3:6].mean()
a6 = arr[3:6, 6: ].mean()

# Going vertical 
a7 = arr[6: , :3].mean()
a8 = arr[6: ,3:6].mean()
a9 = arr[6: , 6: ].mean()

a = [a1, a2, a3, a4, a5, a6, a7, a8, a9]

a_mean = [round(x,1) for x in a]  # Not necessary. Just clean up for the print-out.
#a_mean = list(map(lambda x: round(x,1), a))  # This works too.

print (a_mean)

[37.4, 33.6, 61.0, 40.0, 44.0, 44.4, 44.3, 52.3, 37.8]


### <font color=green>Approach 2: using for loop to reduce the code size

In [18]:
n = 3
arr_1 = np.zeros((9,9))

for i in range(n):
    for j in range(n):
        arr_1[i, j] = np.mean(arr[i*n:(i+1)*n, j*n:(j+1)*n])
        print (round(arr_1[i,j],1))

37.4
33.6
61.0
40.0
44.0
44.4
44.3
52.3
37.8


### <font color=green>Better One

In [19]:
## Use list comprehension to create 9 3x3 subblocks

subblocks = [arr[i:i+3, j:j+3] for i in range(0,9,3) for j in range (0,9,3)]

mean = [round(np.mean(b), 1) for b in subblocks]

print (mean)

[37.4, 33.6, 61.0, 40.0, 44.0, 44.4, 44.3, 52.3, 37.8]


<h4>Q3.2 What is the maximum value in the array? What is the index of the maximum value?</h4>
<h4>Note: use argmax().

### <font color=green> I will accept the answer from a "flattened" array.

In [24]:
max_val = arr.max()
print ("maximum value =", max_val, "on index ", arr.argmax())

maximum value = 98 on index  66


### <font color=green> Or you convert it to 2D index.

In [25]:
def num_2_index(n,row):
    
    x = n//row   # This yields the row index
    y = n % row  # This yields the column index
    return (x, y)

n_row, n_col = arr.shape  # Get the number of rows and number of columns
(x1, y1) = num_2_index(arr.argmax(), n_row)

print ("maximum value =", arr.max(), "on index", (x1, y1)) 

maximum value = 98 on index (7, 3)


### <font color=green> Or use `np.unravel_index` to onverts a flattened index into a tuple of coordinate arrays.

In [27]:
idx = np.unravel_index(arr.argmax(), arr.shape, order='C')   # The order is defaulted as "C"

print ("maximum value =", arr.max(), "on index", idx) 

maximum value = 98 on index (7, 3)


<h3>Q4: Rolling Dices (20 Points)</h3>
    
Assume that you have a fair dice of six faces, that is, it is equally likely to get any of the 6 possible outcomes for one dice roll.

__Q4.1 (5 points): Applying the same method that we used for coin tosses, write a code to simulate the probability of occurrence for each of the 6 numbers. You will perform at least 1,000,000 rolls.__

The result should be presented as follows:
   * Number of 1's = 100,000. Probability = 16.67%
   * Number of 2's = 96,000. Probability = 16.0%
   * ......

In [28]:
# Create a random integer array of values from 1 to 6 with equal probability

n_rolls = 1000000

roll = np.random.randint(1,7, size=n_rolls)
# np.unique(arr, return_counts = True): a useful way to find unique elements and count # of occurrences
outcome, counts = np.unique(roll, return_counts=True)
#print (outcome, counts)

for i in outcome:
    print (f"Number of {i}'s =", counts[i-1], 
           f"\t Probability = {round(counts[i-1]/n_rolls*100,2)}%")

Number of 1's = 166286 	 Probability = 16.63%
Number of 2's = 166305 	 Probability = 16.63%
Number of 3's = 166646 	 Probability = 16.66%
Number of 4's = 166557 	 Probability = 16.66%
Number of 5's = 167246 	 Probability = 16.72%
Number of 6's = 166960 	 Probability = 16.7%


__Q4.2 (7 points): Suppose you are rolling two dices and add the two numbers together. The possible 11 outcomes range from 2 (1+1) to 12 (6+6).__ 

Write a simulation of 1,000,000 trials to find out the probability for each of the 11 outcomes.

The result should be presented as follows:
   * Number of 2's = 14,000. Probability = 2.80%
   * Number of 3's = 27,800. Probability = 5.56%
   * .....

In [3]:
n_rolls = 1000000

# Create two indepedenet dice rolling arrays then add two outcomes together
dice_1 = np.random.randint(1,7, size=n_rolls)
dice_2 = np.random.randint(1,7, size=n_rolls)
dice = dice_1 + dice_2

# Again, use np.unique()
outcome, counts = np.unique(dice, return_counts=True)

for i in outcome:
    print (f"Number of {i}'s =".format(i), counts[i-2], 
           f"\t Probability = {round(counts[i-2]/n_rolls*100, 2)}%")

Number of 2's = 28081 	 Probability = 2.81%
Number of 3's = 55960 	 Probability = 5.6%
Number of 4's = 83264 	 Probability = 8.33%
Number of 5's = 111601 	 Probability = 11.16%
Number of 6's = 138582 	 Probability = 13.86%
Number of 7's = 165805 	 Probability = 16.58%
Number of 8's = 138892 	 Probability = 13.89%
Number of 9's = 110982 	 Probability = 11.1%
Number of 10's = 83340 	 Probability = 8.33%
Number of 11's = 55743 	 Probability = 5.57%
Number of 12's = 27750 	 Probability = 2.78%


__Q4.3 (8 points): Suppose you roll an uneven dice 5 times, what is the probability of getting '4' exactly 3 times? The probability for each face of the dice is as follows.__

      * P(1) = 0.10, P(2) = 0.15, P(3)=0.20, P(4) = 0.25, P(5) = 0.20, P(6) = 0.10

Write a simulation of 1,000,000 trials for the answer.

In [29]:
n_rolls = 1000000
outcome = 0

# For non-uniformly distributed random process, we will use np.random.choice()
p = np.array([0.1, 0.15, 0.2, 0.25, 0.2, 0.1])
a = np.arange(1, 7, dtype=int)

# We want to find out if "4" occurs exactly 3 times in 5 rolls

for _ in np.arange(n_rolls):
    roll_5 = np.random.choice(a,p=p, size=5)   # One trial = 5 rolls of dice
    bool6 = roll_5 == 4     # A boolean array to count the number of True 
    if bool6.sum() == 3:
        outcome += 1

print (f'Prob. of rolling 4 for exactly 3 times = {round(outcome/n_rolls*100, 3)}%')

Prob. of rolling 4 for exactly 3 times = 8.748%


<h3>Q5: Picking Marbles (20 Points)</h3>

__Q5.1 (10 points): You have a bag of 12 marbles, 6 are red, 4 are white, and 2 are blue. You randomly pick three marbles from the bag. What is the probability of drawing 1 red, 1 white, and 1 blue (in this order)? The theoretical result is 2/55 ~3.636%. Write a simulation of 100,000 trials to verify the answer.__ 

Hint: You can follow the steps here:
1. Create an array of 12 elements, bag = np.array(['r','r','r','r','r','r','w','w','w','w','b','b'])
2. Create the desired outcome of 3 marbels of red, white, and blue, bag3 = np.array(['r','w','b'])
3. For each of the trial, you use np.random.permutation() to shuffle the bag array
4. Create a Boolean array by comparing the first three elements of the shuffled array with the desired outcome.
5. If the values the Boolean array are all True --> you have a match

In [30]:
 # Create an array of 12 elements, with 6 red, 4 white, and 2 blue 
bag = np.array(['r','r','r','r','r','r','w','w','w','w','b','b'])

# pattern_3 = the sequence of the first 3 marbels picked
pattern_3 = np.array(['r','w','b'])

print ('First three marbles =', pattern_3)

n_trials = 100000
outcome = 0

for _ in np.arange(n_trials):
    shuffle = np.random.permutation(bag)   # shuffle the order before each trial

    # test if the first three marbles match the pattern
    bool = pattern_3 == shuffle[:3]
    # There is a match if all boolean array values are True
    if bool.all(): outcome += 1
    
print (f'Prob. of red-white-blue = {round(outcome/n_trials*100, 2)}%')

First three marbles = ['r' 'w' 'b']
Prob. of red-white-blue = 3.58%


__Q5.2 (10 points) With the same bag, you again pick out three marbles. However, the order does not matter this time. What is the probability of drawing 1 red, 1 white, and 1 blue? The theoretical result is 12/55 ~21.82%. Write a simulation of 100,000 trials to verify the answer.__

Hint: This question is different from Q5.1 since the order of the drawing is not important as long as you have {r,w,b} in the outcome. You should look for another way to compare the desired outcome with the shuffled arrays.

In [31]:
pattern_3 = np.array(['r','w','b'])
n_trials = 100000
outcome = 0

for i in np.arange(n_trials):
    shuffle =np.random.permutation(bag)

    # The key is to check whether a red, a white, and a blue are picked, so the best way
    # is to use the Python membership command (in). I choose to use np.isin(arr1, arr2) which
    # returns a Boolean array that indicates if elelments in arr1 are in arr2
    bool = np.isin(pattern_3, shuffle[:3])
    if bool.all():
        outcome += 1
    
print (f'Prob. = {round(outcome/n_trials*100, 2)}%')

Prob. = 21.76%


### Q6: Birthday Problem & Normal Distribution (23 Points)

__Q6.1 (7 points) With 30 people in the same room, what is the probability that at least three people are sharing the same birthday? Write a simulation of 100,000 trials to find the answer.__

In [35]:
# Create a uniformly distributed array of N, each with number from 1 to 365 
# Assuming Feb 29 is not a birthday to simplify the simulation.

size = 30   # number of people in a group      
n_trials = 100000
same_bday = 0

# This turns out to be more complicated than the case of "at least 2".
# At least 3 share the same birthday, meaning, we want to remove two cases:
#    1. All have unique birthdays
#.   2. Exactly 2 people share the same birthday
#    How to simulate this?

for _ in np.arange(n_trials):
    bday = np.random.randint(1,366,size)  # random number from 1 to 365

    u, u_count = np.unique(bday, return_counts=True)    # get the unique birthdays & the number for each birthday
    #print (u_count)  
    # As long as there is one u_count >=3, Eureka!
    bool = u_count >= 3 
    if bool.any(): same_bday +=1

print ("Number of people in a group: ", size)
print ("Prob of at least three people share the same birthday = ", same_bday/n_trials)

Number of people in a group:  30
Prob of at least three people share the same birthday =  0.02882


__Q6.2 (8 points) With 30 people in the same room, what is the probability that Exactly three people are sharing the same birthday? Write a simulation of 100,000 trials to find the answer.__

In [36]:
# If you solve the first problem, this one is straigtforward.

# You only need to identify the case where u_count == 3 and it only happens once

size = 30   # number of people in a group      
n_trials = 100000
same_bday = 0

for _ in np.arange(n_trials):
    bday = np.random.randint(1,366,size)  # random number from 1 to 365

    u, u_count = np.unique(bday, return_counts=True)    # get the unique birthdays & the number for each birthday

    # if there is only one u_count = 3, then that's it 
    bool = u_count == 3 
    if (bool.sum() == 1): same_bday +=1

print ("Number of people in a group: ", size)
print ("Prob of exactly three people share the same birthday = ", same_bday/n_trials)

Number of people in a group:  30
Prob of exactly three people share the same birthday =  0.02772


<font color=green> Observation: there is not much difference between those two cases. 
    
<font color=green>This is due to the rarity of having more than 3 people in a 30-people group to share the same birthday. If the group has more than 80, the difference will be much more significant. Give it a try.

__Q6.3 (8 poins) A company produces light bulbs, and the weight of each bulb is normally distributed with a mean of 50 grams and a standard deviation of 2 grams. If the company wants to package the bulbs in boxes of 10, what is the probability that the total weight of the bulbs in a box is between 495 and 505 grams? Write a simulation of 100,000 trials to answer this.__

In [37]:
n_trials = 100000
size = 10
good = 0

for _ in range(n_trials):
    box = np.random.normal(50, 2, size)
    weight = box.sum()
    if ( (weight >= 495) & (weight <= 505)): good += 1
        
print ("Prob of box weight between 495 & 505 grams = ", good/n_trials)

Prob of box weight between 495 & 505 grams =  0.57201
